version: '3.4'
services:
  scope:
    image: weaveworks/weave:latest
    network_mode: "host"
    privileged: true
    ports:
      - "4040:4040"
    labels:
      works.weave.role: "system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
