server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andriizachepilo/azure-webclinic/tree/main/kubernetes/config
          default-label: main

        native:
          searchLocations: file:///${GIT_REPO}

