pipeline {
    agent any

    environment {
        MAVEN_HOME = tool 'Maven321'
        registryCredential = 'docker'
    }

    stages {
        stage('Build') {
            steps {
                dir('services') {
                    script {
                        sh "${MAVEN_HOME}/bin/mvn clean package -DskipTests"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                dir('services') {
                    script {
                        sh "${MAVEN_HOME}/bin/mvn test" 
                    }
                }
            }
        }
        stage('Initialize') {
            steps {
                script {
                    def dockerHome = tool 'myDocker'
                    env.PATH = "${dockerHome}/bin:${env.PATH}"
                }
            }
        }
        stage('Build Images') {
            steps {
                script {docker.withRegistry('', registryCredential) {
                        sh "bash tetsscript.sh"
                    }
                }
            }
        }
        stage('Tag and Push Images') {
            steps {
                script {
                    sh "bash pushtest.sh"
                }
            }
        }
        stage('Deployment') {
            steps {
                script {
                    sh "bash deploy.sh"
                }
            }
        }
    }
}
