pipeline {
    agent any

environment {
    MAVEN_HOME = tool 'Maven321'
}
    stages {
        stage('Build Test') {
            steps {
                dir('pipli') {
                script {
                    sh "${MAVEN_HOME}/bin/mvn clean package -DskipTests"
                    sh "${MAVEN_HOME}/bin/mvn test" 
                }
            }
        }}
        stage('Build Tag Push Images') {
            steps {
                script {
                    sh "bash dockerbuild.sh"
                    sh "bash dockerpush.sh"
                }
            }
        }
        stage('Deployment') {
            steps {
                script {
                    sh "bash deploy.sh"
                }
            }
        }
    }
}
