server:
  port: 9090

---
spring:
  config:
    activate:
      on-profile: default
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server.default.svc.cluster.local:8761/eureka/}

