apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server
  template:
    metadata:
      labels:
        app: admin-server
    spec:
      containers:
      - name: admin-server
        image: acrukwestuniq.azurecr.io/webclinic:admin-server1
        ports:
        - containerPort: 9090
        env:
        - name: CONFIG_SERVER_URL
          value: http://config-server.default.svc.cluster.local:8888
        - name: SPRING_PROFILES_ACTIVE
          value: docker
      nodeSelector: 
        type: Internal