apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
      - name: api-gateway
        image: acrukwestuniq.azurecr.io/webclinic:api-gateway1
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_SERVER_URL
          value: http://config-server.default.svc.cluster.local:8888
        - name: SPRING_PROFILES_ACTIVE
          value: docker
      nodeSelector: 
        type: Public