apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
        - name: jenkins-home
          mountPath: /var/jenkins_home
      - name: docker
        image: docker:19.03
        args: ["dockerd", "-H unix:///var/run/docker.sock"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
      volumes:
      - name: docker-socket
        emptyDir: {}
      - name: jenkins-home
        emptyDir: {}
