apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
      - name: vets-service
        image: andrey342/day4:vets-service1
        ports:
        - containerPort: 8807
        env:
        - name: CONFIG_SERVER_URL
          value: http://config-server.default.svc.cluster.local:8888
        - name: SPRING_PROFILES_ACTIVE
          value: docker,mysql
      nodeSelector: 
        type: Internal
