spring:
  application:
    name: customers-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:config-server.default.svc.cluster.local:80}


---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
